### ISSUE TITLE
AttributeError: module 'httpx' has no attribute 'TimeoutException'

### ISSUE THREAD

**Issue by aimedey19** [Tobi-De/falco_blueprint_basic_bootstrap#11]
The following exception is raised when trying to initialize a new project
`
Traceback (most recent call last):
  File "/Users/aimedegbey/.pyenv/versions/3.10.2/bin/falco", line 8, in <module>
    sys.exit(main())
  File "/Users/aimedegbey/.pyenv/versions/3.10.2/lib/python3.10/site-packages/falco/__main__.py", line 33, in main
    cappa.invoke(Falco)
  File "/Users/aimedegbey/.pyenv/versions/3.10.2/lib/python3.10/site-packages/cappa/base.py", line 141, in invoke
    with resolved.get(concrete_output) as value:
  File "/Users/aimedegbey/.pyenv/versions/3.10.2/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/aimedegbey/.pyenv/versions/3.10.2/lib/python3.10/site-packages/cappa/invoke.py", line 65, in get
    result = callable(**finalized_kwargs)
  File "/Users/aimedegbey/.pyenv/versions/3.10.2/lib/python3.10/site-packages/falco/commands/start_project.py", line 124, in __call__
    with suppress(cappa.Exit, httpx.TimeoutException, httpx.ConnectError):
AttributeError: module 'httpx' has no attribute 'TimeoutException'
`

**Comment by Tobi-De** [comment]
reminder to myself, require a recent version of httpx
